version: '3.9'

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./requirements/nginx/ssl:/etc/nginx/ssl
    networks:
      - app-network
    depends_on:
      - wordpress

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      ADMIN_DB_PASSWORD: ${ADMIN_DB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - app-network
    depends_on:
      - mariadb

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
  wordpress-data:
